name: wisata_batam
description: Aplikasi wisata untuk Kota Batam.
publish_to: 'none' # Ubah jika Anda mempublikasikan aplikasi ini

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Paket untuk peta Google Maps
  google_maps_flutter: ^2.0.6

  http: ^1.2.2

  flutter_local_notifications: ^14.0.0


  # Paket untuk state management yang sederhana (jika diperlukan)
  provider: ^6.0.5

  # Paket untuk menampilkan gambar dan video dari URL
  cached_network_image: ^3.2.0

  # Paket untuk menangani akses lokasi
  geolocator: ^8.2.1

  # Paket untuk menangani format tanggal dan waktu
  intl: ^0.18.1

  # Paket untuk menggunakan fitur native Android dan iOS
  # Anda mungkin tidak memerlukannya tergantung pada kebutuhan Anda
  # flutter_native_splash: ^2.0.5

  # Paket untuk memudahkan pengembangan UI
  flutter_staggered_grid_view: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/